set_property BITSTREAM.General.UnconstrainedPins {Allow} [current_design]

set_property PACKAGE_PIN U14 [get_ports showreg[7]]
set_property PACKAGE_PIN U19 [get_ports showreg[6]]
set_property PACKAGE_PIN W22 [get_ports showreg[5]]
set_property PACKAGE_PIN V22 [get_ports showreg[4]]
set_property PACKAGE_PIN U21 [get_ports showreg[3]]
set_property PACKAGE_PIN U22 [get_ports showreg[2]]
set_property PACKAGE_PIN T21 [get_ports showreg[1]]
set_property PACKAGE_PIN T22 [get_ports showreg[0]]

set_property PACKAGE_PIN M15 [get_ports showaddr[6]]
set_property PACKAGE_PIN H17 [get_ports showaddr[5]]
set_property PACKAGE_PIN H18 [get_ports showaddr[4]]
set_property PACKAGE_PIN H19 [get_ports showaddr[3]]
set_property PACKAGE_PIN F21 [get_ports showaddr[2]]
set_property PACKAGE_PIN H22 [get_ports showaddr[1]]
set_property PACKAGE_PIN G22 [get_ports showaddr[0]]

set_property PACKAGE_PIN P16 [get_ports clk]
set_property PACKAGE_PIN F22 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports showreg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports showreg[7]]

set_property IOSTANDARD LVCMOS18 [get_ports showaddr[0]]
set_property IOSTANDARD LVCMOS18 [get_ports showaddr[1]]
set_property IOSTANDARD LVCMOS18 [get_ports showaddr[2]]
set_property IOSTANDARD LVCMOS18 [get_ports showaddr[3]]
set_property IOSTANDARD LVCMOS18 [get_ports showaddr[4]]
set_property IOSTANDARD LVCMOS18 [get_ports showaddr[5]]
set_property IOSTANDARD LVCMOS18 [get_ports showaddr[6]]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports writedata]
set_property IOSTANDARD LVCMOS18 [get_ports dataaddr]
set_property IOSTANDARD LVCMOS18 [get_ports memwrite]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]