#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Nov 16 21:47:46 EST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f6ee17d75d7c4d648d0ffb16fde6d4d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot PROCESSOR_behav xil_defaultlib.PROCESSOR xil_defaultlib.glbl -log elaborate.log"
xelab -wto f6ee17d75d7c4d648d0ffb16fde6d4d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot PROCESSOR_behav xil_defaultlib.PROCESSOR xil_defaultlib.glbl -log elaborate.log

